# Generated by Django 4.0.1 on 2024-02-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCHEMEREQUEST', models.IntegerField()),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Reqstatus',
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(default='0x45b5f15046FD67E4fcA139cC2fCACF0068E51599', max_length=500),
            preserve_default=False,
        ),
    ]
