# Generated by Django 4.0.1 on 2024-02-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_requeststatus_delete_reqstatus_user_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='requeststatus',
            name='Amount',
            field=models.FloatField(default=0),
        ),
    ]
