# Generated by Django 4.0.1 on 2024-02-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_requeststatus_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCHEMEREQUEST', models.IntegerField()),
                ('Date', models.DateField()),
                ('Amount', models.FloatField()),
                ('Status', models.CharField(max_length=100)),
                ('Sender', models.CharField(max_length=100)),
                ('Reciever', models.CharField(max_length=100)),
            ],
        ),
    ]
